dist: xenial
language: python
python:
- '3.7'
install:
- pip install -r requirements.txt
- nvm install node
script:
- python main.py
before_install:
- openssl aes-256-cbc -K $encrypted_457f57d520f8_key $encrypted_457f57d520f8_iv
  -in key.json.enc -out key.json -d
